server:
  port: 80
  tomcat:
    max-http-form-post-size: 10GB

spring:
  application:
    name: KBoard

  # Thymeleaf ??
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  # datasource ??. MySql? spring-jdbc ??? ?? ?? ??? ???? ??.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${rds.username}
    password: ${rds.password}

  # security
  security:
    user:
      name : user
      password: 1234

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: xxxx
            client-secret: xxxx
            scope:
              - email
              - profile # '- 블라블라' <=배열과 같은 형식
          facebook:
            client-id: xxxx
            client-secret: xxxx
            scope:
              - email
              - public_profile

          naver:
            client-id: xxxx
            client-secret: xxxx
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver


        # provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


  servlet:
    multipart:
      max-file-size: 10GB # 요청 파일 하나의 최대 크기
      max-request-size: 10GB # 요청 파일들 총합의 최대 크기

# MyBatis ??(mapper) ?? ?? ??
# src/main/resources ??? ?? ??
mybatis:
  mapper-locations: classpath:mapper/**/*.xml


app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 10   # 한 [페이징] 당 몇개의 페이지가 표시되나?
    page_rows: 10   # 한 '페이지' 에 몇개의 글을 리스트 할것인지?

  # 파일 업로드 경로
  upload:
    path: upload


  #OAuth2
  oauth2:
    # 공통 비번
    password: xxxx # 보안주의!!!


    # kakao 로그인 관련 세팅값
    kakao:
      client-id: xxxx # app key
      redirect-uri: http://localhost:8080/oauth2/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token	# Access Token 요청 URI
      user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 profile 요청
